### ISSUE TITLE
ウォーターサーバの設置

### ISSUE THREAD

**Issue by gensatonit** [siramatu/LabRules#21]

**Comment by Shingo-Muta** [comment]
欲しいです。研究室にわざわざ水分を持ってこなくてよくなるのは助かります。

**Comment by YuSakai12** [comment]
お湯も出る奴だと便利でいいですね

**Comment by gensatonit** [comment]
使う人と使わない人が出てくるので集金方法を考える必要がありますね

**Comment by SoraMatsumoto** [comment]
水(飲料水)は供給されるなら便利だと思います。個人的には同じ建物の同じ階にそのような水道があれば十分と思うのですが、これは研究室の範疇から外れるかもしれません

**Comment by YuSakai12** [comment]
軽く調べたところ、月々3000円～5000円くらいらしいです。
